# Generated by Django 4.1.7 on 2023-03-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mago',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('magic_affinity', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grimorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grimorio', models.CharField(max_length=255)),
                ('front_page', models.CharField(max_length=255)),
                ('mago_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grimorio.mago')),
            ],
        ),
    ]
