# Generated by Django 4.1.7 on 2023-03-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grimorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grimorio',
            old_name='front_page',
            new_name='front',
        ),
        migrations.RenameField(
            model_name='grimorio',
            old_name='grimorio',
            new_name='grimo',
        ),
        migrations.RenameField(
            model_name='mago',
            old_name='magic_affinity',
            new_name='magic_aff',
        ),
    ]
